export const chartData = {
  month: [
    {
      period: 'September',
      academic: {
        appointments: 375,
        canceled: 8,
        completed: 360,
        expired: 7,
        online: 170,
        offline: 205,
        active: 320,
        passive: 55,
      },
      nonAcademic: {
        appointments: 365,
        canceled: 10,
        completed: 350,
        expired: 5,
        online: 160,
        offline: 205,
        active: 310,
        passive: 55,
      },
    },
    {
      period: 'October',
      academic: {
        appointments: 355,
        canceled: 12,
        completed: 340,
        expired: 3,
        online: 150,
        offline: 205,
        active: 300,
        passive: 55,
      },
      nonAcademic: {
        appointments: 345,
        canceled: 15,
        completed: 325,
        expired: 5,
        online: 140,
        offline: 205,
        active: 290,
        passive: 55,
      },
    },
    {
      period: 'November',
      academic: {
        appointments: 360,
        canceled: 10,
        completed: 345,
        expired: 5,
        online: 160,
        offline: 200,
        active: 310,
        passive: 50,
      },
      nonAcademic: {
        appointments: 355,
        canceled: 12,
        completed: 340,
        expired: 3,
        online: 150,
        offline: 205,
        active: 300,
        passive: 55,
      },
    },
    
  ],
  week: [
    {
      period: 'Monday',
      academic: {
        appointments: 30,
        canceled: 2,
        completed: 25,
        expired: 3,
        online: 15,
        offline: 15,
        active: 20,
        passive: 10,
      },
      nonAcademic: {
        appointments: 25,
        canceled: 3,
        completed: 20,
        expired: 2,
        online: 10,
        offline: 15,
        active: 18,
        passive: 7,
      },
    },
    {
      period: 'Tuesday',
      academic: {
        appointments: 35,
        canceled: 1,
        completed: 32,
        expired: 2,
        online: 18,
        offline: 17,
        active: 25,
        passive: 10,
      },
      nonAcademic: {
        appointments: 28,
        canceled: 2,
        completed: 25,
        expired: 1,
        online: 14,
        offline: 14,
        active: 22,
        passive: 6,
      },
    },
    {
      period: 'Wednesday',
      academic: {
        appointments: 40,
        canceled: 2,
        completed: 38,
        expired: 0,
        online: 20,
        offline: 20,
        active: 30,
        passive: 10,
      },
      nonAcademic: {
        appointments: 35,
        canceled: 3,
        completed: 30,
        expired: 2,
        online: 15,
        offline: 20,
        active: 27,
        passive: 8,
      },
    },
    {
      period: 'Thursday',
      academic: {
        appointments: 45,
        canceled: 3,
        completed: 42,
        expired: 0,
        online: 25,
        offline: 20,
        active: 35,
        passive: 10,
      },
      nonAcademic: {
        appointments: 40,
        canceled: 2,
        completed: 37,
        expired: 1,
        online: 20,
        offline: 20,
        active: 32,
        passive: 8,
      },
    },
    {
      period: 'Friday',
      academic: {
        appointments: 50,
        canceled: 4,
        completed: 45,
        expired: 1,
        online: 30,
        offline: 20,
        active: 40,
        passive: 10,
      },
      nonAcademic: {
        appointments: 45,
        canceled: 3,
        completed: 40,
        expired: 2,
        online: 22,
        offline: 23,
        active: 35,
        passive: 10,
      },
    },
    {
      period: 'Saturday',
      academic: {
        appointments: 55,
        canceled: 5,
        completed: 50,
        expired: 0,
        online: 30,
        offline: 25,
        active: 45,
        passive: 10,
      },
      nonAcademic: {
        appointments: 50,
        canceled: 4,
        completed: 45,
        expired: 1,
        online: 25,
        offline: 25,
        active: 40,
        passive: 10,
      },
    },
    {
      period: 'Sunday',
      academic: {
        appointments: 20,
        canceled: 1,
        completed: 18,
        expired: 1,
        online: 10,
        offline: 10,
        active: 15,
        passive: 5,
      },
      nonAcademic: {
        appointments: 15,
        canceled: 1,
        completed: 13,
        expired: 1,
        online: 8,
        offline: 7,
        active: 10,
        passive: 5,
      },
    },
  ],
  day: [
    {
      period: '2024/16/11',
      academic: {
        appointments: 10,
        canceled: 0,
        completed: 8,
        expired: 2,
        online: 5,
        offline: 5,
        active: 7,
        passive: 3,
      },
      nonAcademic: {
        appointments: 8,
        canceled: 1,
        completed: 7,
        expired: 0,
        online: 4,
        offline: 4,
        active: 6,
        passive: 2,
      },
    },
  ],
};
